spring:
  datasource:
    url: jdbc:mysql://localhost/projeto_integrador?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update